# Generated by Django 5.2.2 on 2025-06-09 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('aberta', 'Em aberto'), ('analise', 'Em análise'), ('fechada', 'Fechada')], default='aberta', max_length=10)),
                ('data_os', models.DateField(default=django.utils.timezone.now)),
                ('previsao_entrega', models.DateField()),
                ('canal_venda', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=10)),
                ('equipamento', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('condicoes', models.TextField(blank=True)),
                ('defeitos', models.TextField(blank=True)),
                ('acessorios', models.TextField(blank=True)),
                ('solucao', models.TextField(blank=True)),
                ('laudo_tecnico', models.TextField(blank=True)),
                ('termos_garantia', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.cliente')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordem_servico.funcionario')),
            ],
        ),
    ]
