# Generated by Django 5.2.2 on 2025-06-17 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0002_alter_cliente_nome_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hora_criacao',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
